Repository HwanYulMate/HwanYulMate-iOS, pull requests merged in 2025-09, with the labels that each got.

#31 [Refactor] 로그인 설계구조에 맞춰 로그아웃&회원탈퇴 기능 수정 외
  HwanYulMate.xcodeproj/project.pbxproj
  HwanYulMate/Data/DataSource/Local/AuthLocalDataSourceImpl.swift
  HwanYulMate/Presentation/News/NewsModel.swift
  HwanYulMate/Presentation/News/NewsNetworkService.swift
  HwanYulMate/Presentation/News/NewsViewController.swift
  HwanYulMate/Presentation/Profile/APIErrorResponse.swift
  HwanYulMate/Presentation/Profile/Feedback/FeedbackViewController.swift
  HwanYulMate/Presentation/Profile/Logout/LogoutViewController.swift
  HwanYulMate/Presentation/Profile/OpenSourceLicense/OpenSourceLicenseView.swift
  HwanYulMate/Presentation/Profile/PrivacyPolicy/PrivacyPolicyViewController.swift
  HwanYulMate/Presentation/Profile/ProfileCell.swift
  HwanYulMate/Presentation/Profile/ProfileNetworkService.swift
  HwanYulMate/Presentation/Profile/ProfileViewController.swift
  HwanYulMate/Presentation/Profile/UserInfoManager.swift
  HwanYulMate/Presentation/Profile/Withdrawal/WithdrawalView.swift
  HwanYulMate/Presentation/Profile/Withdrawal/WithdrawalViewController.swift
  HwanYulMate/Presentation/TabBar/TabBarViewController.swift
Labels: Bug Fix, Chore, Refactor, Add, Feat

#33 Feat/#30
  HwanYulMate.xcodeproj/project.pbxproj
  HwanYulMate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HwanYulMate/Application/AppDelegate.swift
  HwanYulMate/Application/SceneDelegate.swift
  HwanYulMate/Data/DataSource/Remote/AlertSettingsRemoteDataSourceImpl.swift
  HwanYulMate/Data/DataSource/Remote/AuthRemoteDataSourceImpl.swift
  HwanYulMate/Data/DataSource/Remote/ExchangeRateRemoteDataSourceImpl.swift
  HwanYulMate/Data/Network/AuthEndpoint.swift
  HwanYulMate/Data/Network/DailyAlertEndpoint.swift
  HwanYulMate/Data/Network/DataMapping/DailyAlertRequestDTO+Mapping.swift
  HwanYulMate/Data/Network/DataMapping/DailyAlertResponseDTO+Mapping.swift
  HwanYulMate/Data/Network/DataMapping/FCMRequestDTO+Mapping.swift
  HwanYulMate/Data/Network/DataMapping/TargetPriceRequestDTO+Mapping.swift
  HwanYulMate/Data/Network/DataMapping/TargetPriceResponseDTO+Mapping.swift
  HwanYulMate/Data/Network/TargetPriceEndpoint.swift
  HwanYulMate/Data/Repository/AlertSettingsRepositoryImpl.swift
  HwanYulMate/Data/Repository/AuthRepositoryImpl.swift
  HwanYulMate/Data/Repository/ExchangeRateRepositoryImpl.swift
  HwanYulMate/Domain/Entity/DailyAlert.swift
  HwanYulMate/Domain/Entity/News.swift
  HwanYulMate/Domain/Entity/TargetPrice.swift
  HwanYulMate/Domain/Interface/Repository/AlertSettingsRepository.swift
  HwanYulMate/Domain/Interface/Repository/ExchangeRateRepository.swift
  HwanYulMate/HwanYulMate.entitlements
  HwanYulMate/Infrastructure/SocialLogin/GoogleLoginService.swift
  HwanYulMate/Infrastructure/Storage/TokenStorage.swift
  HwanYulMate/Presentation/Home/HomeView.swift
  HwanYulMate/Presentation/HomeDetail/HomeDetailReactor.swift
  HwanYulMate/Presentation/HomeDetail/HomeDetailView.swift
  HwanYulMate/Presentation/Login/LoginReactor.swift
  HwanYulMate/Presentation/Login/LoginViewController.swift
  HwanYulMate/Presentation/Notification/NotificationReactor.swift
  HwanYulMate/Presentation/Notification/NotificationViewController.swift
  HwanYulMate/Presentation/NotificationSetting/BottomSheet/TargetRate/TargetRateBottomSheetReactor.swift
  HwanYulMate/Presentation/NotificationSetting/BottomSheet/TargetRate/TargetRateBottomSheetViewController.swift
  HwanYulMate/Presentation/NotificationSetting/BottomSheet/TimeSelection/TimeSelectionBottomSheetReactor.swift
  HwanYulMate/Presentation/NotificationSetting/BottomSheet/TimeSelection/TimeSelectionBottomSheetView.swift
  HwanYulMate/Presentation/NotificationSetting/BottomSheet/TimeSelection/TimeSelectionBottomSheetViewController.swift
  HwanYulMate/Presentation/NotificationSetting/NotificationSettingReactor.swift
  HwanYulMate/Presentation/NotificationSetting/NotificationSettingView.swift
  HwanYulMate/Presentation/NotificationSetting/NotificationSettingViewController.swift
  HwanYulMate/Resource/GoogleService-Info.plist
  HwanYulMate/Resource/Info.plist
Labels: Feat

#37 Feat/#36
  HwanYulMate.xcodeproj/project.pbxproj
  HwanYulMate/Application/AppDelegate.swift
  HwanYulMate/Application/SceneDelegate.swift
  HwanYulMate/Data/DataSource/Remote/BankRemoteDataSourceImpl.swift
  HwanYulMate/Data/Network/DataMapping/BankResponseDTO+Mapping.swift
  HwanYulMate/Data/Repository/BankRepositoryImpl.swift
  HwanYulMate/Domain/Entity/Bank.swift
  HwanYulMate/Domain/Interface/Repository/BankRepository.swift
  HwanYulMate/Infrastructure/Storage/TokenStorage.swift
  HwanYulMate/Presentation/ExchangeEstimateComparison/ExchangeEstimateComparisonReactor.swift
  HwanYulMate/Presentation/HomeDetail/BottomSheet/ExchangeEstimateComparisonBottomSheetReactor.swift
  HwanYulMate/Presentation/HomeDetail/BottomSheet/ExchangeEstimateComparisonBottomSheetViewController.swift
  HwanYulMate/Presentation/HomeDetail/HomeDetailReactor.swift
  HwanYulMate/Resource/Assets.xcassets/AppIcon.appiconset/Logo.png
Labels: Bug Fix
